/**
 * Izveido programmu, kas atmin datora iedomātu skaitli intervālā no 1 līdz 40,
 * pie katra skaitļa tiek norādīts, vai tas ir par lielu vai mazu.
 * Vai arī lietotājs ievada skaitli un dators to mēģina atminēt.
 * Ieteicams izmantot nevis gadījuma skaitļus minēšanai, bet loģiku.
 */

#include <iostream>
#include <string>
#include <cmath>
using namespace std;

string answer;
int number;

void print_lt_gt_equal( const int& guess_number ) {
	if ( guess_number > number ) {
		cout << "The number is greater than " << guess_number << "\n";
	} else if ( guess_number < number ) {
		cout << "The number is lower than " << guess_number << "\n";
	} else {
		cout << "The number is found! It is " << guess_number << "\n";
	}
}

void capture_answer() {
	cout << "Please enter a number from 1 to 40 or press enter for autogenerated number to be used: ";
	getline( cin, answer );
	if ( answer == "" ) {
	    number = rand() % 40 + 1;
	} else {
		try {
		    number = stoi( answer );
		}
		catch( exception& e ){
		    capture_answer();
		}
		if ( number > 40 || number < 1 ) {
			capture_answer();
		}
	}
}

int find_number() {
	int guess_number, lower_num = 1, upper_num = 40;
	while ( guess_number != number ) {
		guess_number = floor( lower_num + ( upper_num - lower_num ) / 2 );

		print_lt_gt_equal( guess_number );

		if ( guess_number < number ) {
			lower_num = guess_number + 1;
		}

		if ( guess_number > number ) {
			upper_num = guess_number - 1;
		}
	}
	return guess_number;
}

void print_number() {
    cout << "The number computer will try to guess is " << number << "\n\n";
}

int main() {
	srand( time( NULL ) );
	capture_answer();
	print_number();
	find_number();
	return 0;
}